### ISSUE TITLE
Installation Guide 

### ISSUE THREAD

**Issue by sabarish-2020** [NZTA/SDLT#32]
Hi Guys, can anyone share a document on how to setup SDLT on Virtual box - Ubuntu 16.04 (32 Bit). I trying to install this tool.

**Comment by Zaita** [comment]
Hello.
When you're using Ubuntu you can follow the instructions found in the wiki. 
https://github.com/NZTA/SDLT/wiki

If you're familiar with docker, those instructions are the easiest:
https://github.com/NZTA/SDLT/wiki/Installation-Setup-Docker

Otherwise, Apache or Nginx:
https://github.com/NZTA/SDLT/wiki/Installation-Setup-Apache
https://github.com/NZTA/SDLT/wiki/Installation-Setup-Nginx

_Note: I am not sure what containers are available for 32bit Ubuntu. But the docker instructions have been tested in x64 and ARM_

**Comment by sabarish-2020** [comment]
Hi Zaita, Thank you the information. I have one more question.... 

Is it possible to install this tool in a docker desktop on a windows 10 operating system?

**Comment by Zaita** [comment]
This has not been tested. It is likely possible, but we don't have any information on how to accomplish this.

Regards,
Scott.

**Comment by Zaita** [comment]
Closing issue. 7 days with no response.
